# Capital Project Datasets

- Parks: https://data.cityofnewyork.us/Recreation/Capital-Project-Tracker/4hcv-tc5r/about_data
- Capital Planning: https://capitalplanning.nyc.gov/map#12.16/40.6485/-74.0216

Allow us to see where the city is developing and where they are spending

## Department of Parks and Recreation Capital Projects

In [1]:
import pandas as pd
import geopandas as gpd

In [2]:
df_parks = pd.read_csv('raw_data/Capital_Project_Tracker_20250924.csv')
df_parks

,TrackerID,FMSID,Title,Summary,CurrentPhase,DesignPercentComplete,ProcurementPercentComplete,ConstructionPercentComplete,DesignStart,DesignProjectedCompletion,...,ConstructionActualCompletion,TotalFunding,ProjectLiaison,LastUpdated,FundingSource,name,ParkID,Latitude,Longitude,Borough
0,10438,846 P-405VITO,Uncle Vito F. Maranzano Glendale Playground Re...,This project will reconstruct Uncle Vito F. Ma...,procurement,100,60,0.0,05/01/2023 12:00:00 AM,10/01/2024 12:00:00 AM,...,NaN,Between $5 million and $10 million,Meira Berkower,09/22/2025 12:00:00 AM,City Council,Central Avenue between 70th and 71st Street,Q290,40.704964,-73.881725,Queens
1,9578,846 P-3PHILSQ,A. Philip Randolph Square Reconstruction,This project will reconstruct A. Philip Randol...,design,30,0,0.0,10/01/2024 12:00:00 AM,04/01/2026 12:00:00 AM,...,NaN,Greater than $10 million,Steve Simon,09/22/2025 12:00:00 AM,Borough PresidentCity CouncilMayoral,"Adam Clayton Powell Jr. Boulevard, St. Nichola...",M021,40.803901,-73.952413,Manhattan
2,1004111,846 P-4PL15A1,Arrow Recreation Center Playground Reconstruction,This project will reconstruct the playground a...,completed,100,100,100.0,03/01/2015 12:00:00 AM,08/01/2015 12:00:00 AM,...,03/01/2018 12:00:00 AM,"$150,000",Meira Berkower,09/22/2025 12:00:00 AM,Mayoral,NaN,Q470,40.755839,-73.926293,Queens
3,10687,846 P-303ABCP,ABC Playground Reconstruction,This project will reconstruct ABC Playground.,design,5,0,0.0,02/01/2026 12:00:00 AM,07/01/2026 12:00:00 AM,...,NaN,Between $5 million and $10 million,Steve Simon,09/22/2025 12:00:00 AM,City CouncilMayoral,"Essex, Norfolk & Houston Streets",M116,40.721812,-73.985961,Manhattan
4,7121,NaN,Abe Stark Ice Rink Electrical System Reconstru...,This project will reconstruct and elevate the ...,proposed,0,0,0.0,NaN,NaN,...,NaN,Between $1 million and $3 million,James Morris,09/22/2025 12:00:00 AM,FederalMayoral,Coney Island Boardwalk and West 19th Street.,B336,40.573747,-73.985603,Brooklyn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2681,6330,846 P-6PNYR27,Brooklyn and Staten Island Reforestation FY15,This project will remove invasive species and ...,completed,100,100,100.0,06/01/2014 12:00:00 AM,08/01/2014 12:00:00 AM,...,06/01/2018 12:00:00 AM,"$1,030,000",NaN,09/22/2025 12:00:00 AM,"Mayoral, Private",Various parks in Brooklyn and Staten Island,NaN,0.000000,0.000000,NaN
2682,9656,846 P-1WPSOTO,NYCHA Sotomayor Houses Open Space Construction,This project will construct a new open space a...,completed,100,100,100.0,06/01/2021 12:00:00 AM,06/01/2022 12:00:00 AM,...,08/01/2024 12:00:00 AM,"$1,602,000",Katerine Borrome,09/22/2025 12:00:00 AM,Mayoral,Watson Avenue between Taylor Avenue and Thieri...,NaN,40.827779,-73.864155,Bronx
2683,8960,846 P-3PIN181,Pinehurst Avenue Step Street Garden Reconstruc...,This project will reconstruct the garden at th...,construction,100,100,0.0,05/01/2018 12:00:00 AM,05/01/2019 12:00:00 AM,...,NaN,"$649,000",Steve Simon,09/22/2025 12:00:00 AM,Borough PresidentCity CouncilMayoral,West 181st Street and Pinehurst Avenue,DOT,40.851374,-73.939174,Manhattan
2684,9835,846 P-4WOODPZ,Woodside Memorial Plaza Reconstruction,This project will reconstruct Woodside Memoria...,completed,100,100,100.0,01/01/2021 12:00:00 AM,01/01/2022 12:00:00 AM,...,03/01/2025 12:00:00 AM,"$1,749,000",Meira Berkower,09/22/2025 12:00:00 AM,"Borough President, City Council","Woodside Avenue, Roosevelt Avenue, 60th Street",Q198,40.745325,-73.904784,Queens
2685,11122,NaN,Las Casitas Community Garden Water Service Ins...,This project will install water service in Las...,proposed,0,0,0.0,NaN,NaN,...,NaN,Less than $1 million,NaN,09/22/2025 12:00:00 AM,NaN,Woodycrest Avenue between East 166th Street an...,X328,40.835580,-73.925421,Bronx

In [3]:
df_parks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2686 entries, 0 to 2685
Data columns (total 29 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   TrackerID                        2686 non-null   int64
 1   FMSID                            2380 non-null   object
 2   Title                            2686 non-null   object
 3   Summary                          2683 non-null   object
 4   CurrentPhase                     2686 non-null   object
 5   DesignPercentComplete            2686 non-null   int64
 6   ProcurementPercentComplete       2686 non-null   int64
 7   ConstructionPercentComplete      2686 non-null   float64
 8   DesignStart                      2410 non-null   object
 9   DesignProjectedCompletion        2188 non-null   object
 10  DesignAdjustedCompletion         798 non-null    object
 11  DesignActualCompletion           2242 non-null   object
 12  ProcurementStart                 2190 non-null   object
 13  ProcurementProjectedCompletion   2188 non-null   object
 14  ProcurementAdjustedCompletion    1227 non-null   object
 15  ProcurementActualCompletion      2084 non-null   object
 16  ConstructionStart                2064 non-null   object
 17  ConstructionProjectedCompletion  2064 non-null   object
 18  ConstructionAdjustedCompletion   726 non-null    object
 19  ConstructionActualCompletion     1873 non-null   object
 20  TotalFunding                     2686 non-null   object
 21  ProjectLiaison                   2209 non-null   object
 22  LastUpdated                      2686 non-null   object
 23  FundingSource                    2562 non-null   object
 24  name                             2319 non-null   object
 25  ParkID                           2396 non-null   object
 26  Latitude                         2686 non-null   float64
 27  Longitude                        2686 non-null   float64
 28  Borough                          2664 non-null   object
dtypes: float64(3), int64(3), object(23)
memory usage: 608.7+ KB

In [4]:
df_parks = df_parks[['DesignStart', 'CurrentPhase', 'Latitude', 'Longitude', 'Title', 'TotalFunding']]
df_parks

,DesignStart,CurrentPhase,Latitude,Longitude,Title,TotalFunding
0,05/01/2023 12:00:00 AM,procurement,40.704964,-73.881725,Uncle Vito F. Maranzano Glendale Playground Re...,Between $5 million and $10 million
1,10/01/2024 12:00:00 AM,design,40.803901,-73.952413,A. Philip Randolph Square Reconstruction,Greater than $10 million
2,03/01/2015 12:00:00 AM,completed,40.755839,-73.926293,Arrow Recreation Center Playground Reconstruction,"$150,000"
3,02/01/2026 12:00:00 AM,design,40.721812,-73.985961,ABC Playground Reconstruction,Between $5 million and $10 million
4,NaN,proposed,40.573747,-73.985603,Abe Stark Ice Rink Electrical System Reconstru...,Between $1 million and $3 million
...,...,...,...,...,...,...
2681,06/01/2014 12:00:00 AM,completed,0.000000,0.000000,Brooklyn and Staten Island Reforestation FY15,"$1,030,000"
2682,06/01/2021 12:00:00 AM,completed,40.827779,-73.864155,NYCHA Sotomayor Houses Open Space Construction,"$1,602,000"
2683,05/01/2018 12:00:00 AM,construction,40.851374,-73.939174,Pinehurst Avenue Step Street Garden Reconstruc...,"$649,000"
2684,01/01/2021 12:00:00 AM,completed,40.745325,-73.904784,Woodside Memorial Plaza Reconstruction,"$1,749,000"
2685,NaN,proposed,40.835580,-73.925421,Las Casitas Community Garden Water Service Ins...,Less than $1 million

In [5]:
df_parks = df_parks[df_parks['CurrentPhase'] != 'proposed']
df_parks = df_parks[df_parks['Latitude'] != 0]

In [6]:
df_parks

,DesignStart,CurrentPhase,Latitude,Longitude,Title,TotalFunding
0,05/01/2023 12:00:00 AM,procurement,40.704964,-73.881725,Uncle Vito F. Maranzano Glendale Playground Re...,Between $5 million and $10 million
1,10/01/2024 12:00:00 AM,design,40.803901,-73.952413,A. Philip Randolph Square Reconstruction,Greater than $10 million
2,03/01/2015 12:00:00 AM,completed,40.755839,-73.926293,Arrow Recreation Center Playground Reconstruction,"$150,000"
3,02/01/2026 12:00:00 AM,design,40.721812,-73.985961,ABC Playground Reconstruction,Between $5 million and $10 million
5,12/01/2013 12:00:00 AM,completed,40.817299,-73.904724,Bronx and Queens Roofing Systems Reconstructio...,"$1,570,000"
...,...,...,...,...,...,...
2413,10/01/2014 12:00:00 AM,completed,40.828144,-73.902482,Jackson Forest Community Garden Reconstruction,"$361,000"
2414,10/01/2012 12:00:00 AM,completed,40.706862,-74.013860,Elizabeth H. Berger Plaza Construction,"$5,494,000"
2682,06/01/2021 12:00:00 AM,completed,40.827779,-73.864155,NYCHA Sotomayor Houses Open Space Construction,"$1,602,000"
2683,05/01/2018 12:00:00 AM,construction,40.851374,-73.939174,Pinehurst Avenue Step Street Garden Reconstruc...,"$649,000"
2684,01/01/2021 12:00:00 AM,completed,40.745325,-73.904784,Woodside Memorial Plaza Reconstruction,"$1,749,000"

In [7]:
df_parks["TotalFunding"] = (df_parks["TotalFunding"]
    .str.replace("Less than $1 million", "$1,000,000")
    .str.replace("Between $1 million and $3 million", "$2,000,000")
    .str.replace("Between $3 million and $5 million", "$4,000,000")
    .str.replace("Between $5 million and $10 million", "$7,500,000")
    .str.replace("Between $5 million and $8 million", "$6,500,000")
    .str.replace("Greater than $10 million", "$10,000,000")
)

In [8]:
df_parks['TotalFunding'] = df_parks['TotalFunding'].str.replace('$', '').str.replace(',', '').astype(float)
df_parks = df_parks[df_parks['TotalFunding'] > 0]
df_parks

,DesignStart,CurrentPhase,Latitude,Longitude,Title,TotalFunding
0,05/01/2023 12:00:00 AM,procurement,40.704964,-73.881725,Uncle Vito F. Maranzano Glendale Playground Re...,7500000.0
1,10/01/2024 12:00:00 AM,design,40.803901,-73.952413,A. Philip Randolph Square Reconstruction,10000000.0
2,03/01/2015 12:00:00 AM,completed,40.755839,-73.926293,Arrow Recreation Center Playground Reconstruction,150000.0
3,02/01/2026 12:00:00 AM,design,40.721812,-73.985961,ABC Playground Reconstruction,7500000.0
5,12/01/2013 12:00:00 AM,completed,40.817299,-73.904724,Bronx and Queens Roofing Systems Reconstructio...,1570000.0
...,...,...,...,...,...,...
2413,10/01/2014 12:00:00 AM,completed,40.828144,-73.902482,Jackson Forest Community Garden Reconstruction,361000.0
2414,10/01/2012 12:00:00 AM,completed,40.706862,-74.013860,Elizabeth H. Berger Plaza Construction,5494000.0
2682,06/01/2021 12:00:00 AM,completed,40.827779,-73.864155,NYCHA Sotomayor Houses Open Space Construction,1602000.0
2683,05/01/2018 12:00:00 AM,construction,40.851374,-73.939174,Pinehurst Avenue Step Street Garden Reconstruc...,649000.0
2684,01/01/2021 12:00:00 AM,completed,40.745325,-73.904784,Woodside Memorial Plaza Reconstruction,1749000.0

In [9]:
df_parks['DesignStart'] = pd.to_datetime(df_parks["DesignStart"]).dt.year.astype("Int64")
df_parks

C:\Users\Jason\AppData\Local\Temp\ipykernel_20156\3115152039.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_parks['DesignStart'] = pd.to_datetime(df_parks["DesignStart"]).dt.year.astype("Int64")
C:\Users\Jason\AppData\Local\Temp\ipykernel_20156\3115152039.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_parks['DesignStart'] = pd.to_datetime(df_parks["DesignStart"]).dt.year.astype("Int64")

,DesignStart,CurrentPhase,Latitude,Longitude,Title,TotalFunding
0,2023,procurement,40.704964,-73.881725,Uncle Vito F. Maranzano Glendale Playground Re...,7500000.0
1,2024,design,40.803901,-73.952413,A. Philip Randolph Square Reconstruction,10000000.0
2,2015,completed,40.755839,-73.926293,Arrow Recreation Center Playground Reconstruction,150000.0
3,2026,design,40.721812,-73.985961,ABC Playground Reconstruction,7500000.0
5,2013,completed,40.817299,-73.904724,Bronx and Queens Roofing Systems Reconstructio...,1570000.0
...,...,...,...,...,...,...
2413,2014,completed,40.828144,-73.902482,Jackson Forest Community Garden Reconstruction,361000.0
2414,2012,completed,40.706862,-74.013860,Elizabeth H. Berger Plaza Construction,5494000.0
2682,2021,completed,40.827779,-73.864155,NYCHA Sotomayor Houses Open Space Construction,1602000.0
2683,2018,construction,40.851374,-73.939174,Pinehurst Avenue Step Street Garden Reconstruc...,649000.0
2684,2021,completed,40.745325,-73.904784,Woodside Memorial Plaza Reconstruction,1749000.0

In [10]:
gdf = gpd.read_file('raw_data/nycd_25c/nycd.shp')
gdf

,BoroCD,Shape_Leng,Shape_Area,geometry
0,410,105822.377329,1.720774e+08,"MULTIPOLYGON (((1023868.747 176222.723, 102336..."
1,480,47338.740067,3.277756e+07,"POLYGON ((1022276.97 218625.343, 1022251.388 2..."
2,104,67546.045387,4.931005e+07,"POLYGON ((985929.324 220967.002, 985995.954 22..."
3,107,39863.703295,5.315258e+07,"POLYGON ((995422.176 231162.464, 995647.332 23..."
4,317,43327.354912,9.381843e+07,"POLYGON ((1009902.796 176534.51, 1009642.537 1..."
...,...,...,...,...
66,302,73413.339179,7.932007e+07,"POLYGON ((992763.566 196891.144, 992808.718 19..."
67,304,37006.832522,5.666299e+07,"POLYGON ((1012965.523 187886.949, 1012949.003 ..."
68,405,70020.381942,2.103949e+08,"POLYGON ((1015372.06 206818.665, 1015537.002 2..."
69,101,69090.913150,4.169373e+07,"MULTIPOLYGON (((972081.788 190733.467, 972184...."
70,103,30505.700417,4.687884e+07,"POLYGON ((987359.695 206680.171, 987694.33 206..."

In [11]:
from shapely.geometry import Point

geometry = [Point(xy) for xy in zip(df_parks["Longitude"], df_parks["Latitude"])]
gdf_points = gpd.GeoDataFrame(df_parks, geometry=geometry, crs="EPSG:4326").to_crs("EPSG:2263")
gdf_points

,DesignStart,CurrentPhase,Latitude,Longitude,Title,TotalFunding,geometry
0,2023,procurement,40.704964,-73.881725,Uncle Vito F. Maranzano Glendale Playground Re...,7500000.0,POINT (1017042.938 196136.011)
1,2024,design,40.803901,-73.952413,A. Philip Randolph Square Reconstruction,10000000.0,POINT (997424.398 232163.415)
2,2015,completed,40.755839,-73.926293,Arrow Recreation Center Playground Reconstruction,150000.0,POINT (1004670.418 214657.815)
3,2026,design,40.721812,-73.985961,ABC Playground Reconstruction,7500000.0,POINT (988141.472 202252.422)
5,2013,completed,40.817299,-73.904724,Bronx and Queens Roofing Systems Reconstructio...,1570000.0,POINT (1010621.721 237055.546)
...,...,...,...,...,...,...,...
2413,2014,completed,40.828144,-73.902482,Jackson Forest Community Garden Reconstruction,361000.0,POINT (1011237.831 241007.312)
2414,2012,completed,40.706862,-74.013860,Elizabeth H. Berger Plaza Construction,5494000.0,POINT (980407.283 196805.675)
2682,2021,completed,40.827779,-73.864155,NYCHA Sotomayor Houses Open Space Construction,1602000.0,POINT (1021845.003 240888.6)
2683,2018,construction,40.851374,-73.939174,Pinehurst Avenue Step Street Garden Reconstruc...,649000.0,POINT (1001077.587 249461.831)
2684,2021,completed,40.745325,-73.904784,Woodside Memorial Plaza Reconstruction,1749000.0,POINT (1010633.617 210832.973)

In [12]:
gdf_merged = gpd.sjoin(gdf_points, gdf, how="inner", predicate="within")
gdf_merged

,DesignStart,CurrentPhase,Latitude,Longitude,Title,TotalFunding,geometry,index_right,BoroCD,Shape_Leng,Shape_Area
0,2023,procurement,40.704964,-73.881725,Uncle Vito F. Maranzano Glendale Playground Re...,7500000.0,POINT (1017042.938 196136.011),68,405,70020.381942,2.103949e+08
1,2024,design,40.803901,-73.952413,A. Philip Randolph Square Reconstruction,10000000.0,POINT (997424.398 232163.415),16,110,35890.251738,3.907378e+07
2,2015,completed,40.755839,-73.926293,Arrow Recreation Center Playground Reconstruction,150000.0,POINT (1004670.418 214657.815),30,401,91025.495437,1.714433e+08
3,2026,design,40.721812,-73.985961,ABC Playground Reconstruction,7500000.0,POINT (988141.472 202252.422),70,103,30505.700417,4.687884e+07
5,2013,completed,40.817299,-73.904724,Bronx and Queens Roofing Systems Reconstructio...,1570000.0,POINT (1010621.721 237055.546),47,201,33341.876025,6.039980e+07
...,...,...,...,...,...,...,...,...,...,...,...
2413,2014,completed,40.828144,-73.902482,Jackson Forest Community Garden Reconstruction,361000.0,POINT (1011237.831 241007.312),19,203,33499.612461,4.479725e+07
2414,2012,completed,40.706862,-74.013860,Elizabeth H. Berger Plaza Construction,5494000.0,POINT (980407.283 196805.675),69,101,69090.913150,4.169373e+07
2682,2021,completed,40.827779,-73.864155,NYCHA Sotomayor Houses Open Space Construction,1602000.0,POINT (1021845.003 240888.6),33,209,62243.211150,1.142840e+08
2683,2018,construction,40.851374,-73.939174,Pinehurst Avenue Step Street Garden Reconstruc...,649000.0,POINT (1001077.587 249461.831),35,112,54703.672361,7.796357e+07
2684,2021,completed,40.745325,-73.904784,Woodside Memorial Plaza Reconstruction,1749000.0,POINT (1010633.617 210832.973),31,402,72490.037344,1.400101e+08

In [13]:
df = gdf_merged[['DesignStart', 'BoroCD', 'TotalFunding']]
df.sort_values(by='DesignStart')

      DesignStart  BoroCD  TotalFunding
634          2001     313     3152000.0
2077         2005     209     1885000.0
2078         2005     209     1885000.0
1209         2005     503    16175000.0
1551         2005     407     5344000.0
...           ...     ...           ...
1304         2025     303     7500000.0
1618         2025     412     2000000.0
332          2025     202    10000000.0
3            2026     103     7500000.0
1065         <NA>     481     1985000.0

[2128 rows x 3 columns]

In [14]:
top_5 = df[df["BoroCD"].isin([101, 102, 301, 302, 306])]
bottom_5 = df[df["BoroCD"].isin([202, 205, 311, 312, 317])]
len(top_5), len(bottom_5)

(142, 87)

In [15]:
# BAN metrics

top_sum = top_5["TotalFunding"].sum()
bottom_sum = bottom_5["TotalFunding"].sum()
difference = top_sum - bottom_sum
mean = gdf_merged['TotalFunding'].agg('mean')
median = gdf_merged['TotalFunding'].agg('median')
difference, mean, median

(379987000.0, 3325545.582706767, 1986500.0)

In [16]:
gbt5 = top_5.groupby("DesignStart").agg(
    count=("DesignStart", "count"),           
    total_funding=("TotalFunding", "sum")  
).reset_index()

In [17]:
gbb5 = bottom_5.groupby("DesignStart").agg(
    count=("DesignStart", "count"),           
    total_funding=("TotalFunding", "sum")  
).reset_index()

In [18]:
gbt5['group'] = 'top 5'
gbb5['group'] = 'bottom 5'

In [19]:
gbb5["count"] = gbb5["count"].cumsum()
gbb5["total_funding"] = gbb5["total_funding"].cumsum()

gbt5["count"] = gbt5["count"].cumsum()
gbt5["total_funding"] = gbt5["total_funding"].cumsum()

In [20]:
mid_5 = df[df["BoroCD"].isin([414, 405, 408, 307, 316])]

gbm5 = mid_5.groupby("DesignStart").agg(
    count=("DesignStart", "count"),           
    total_funding=("TotalFunding", "sum")  
).reset_index()

gbm5["count"] = gbm5["count"].cumsum()
gbm5["total_funding"] = gbm5["total_funding"].cumsum()

gbm5['group'] = 'middle 5'

gbm5

    DesignStart  count  total_funding     group
0          2006      5     15686000.0  middle 5
1          2008      9     28058000.0  middle 5
2          2009     11     32307000.0  middle 5
3          2010     17     40033000.0  middle 5
4          2011     27     61423000.0  middle 5
5          2012     29     63919000.0  middle 5
6          2013     39     71209000.0  middle 5
7          2014     52    112711000.0  middle 5
8          2015     72    171080000.0  middle 5
9          2016     85    223358000.0  middle 5
10         2017     94    259401000.0  middle 5
11         2018    126    436496000.0  middle 5
12         2019    137    467278000.0  middle 5
13         2020    151    507655000.0  middle 5
14         2021    156    509869000.0  middle 5
15         2022    167    530110000.0  middle 5
16         2023    178    582660000.0  middle 5
17         2024    187    623474000.0  middle 5
18         2025    189    638474000.0  middle 5

In [21]:
gb = pd.concat([gbb5, gbt5, gbm5])
gb

    DesignStart  count  total_funding     group
0          2006      1      1238000.0  bottom 5
1          2008      3      2929000.0  bottom 5
2          2009      4      8105000.0  bottom 5
3          2010     12     16723000.0  bottom 5
4          2011     18     27727000.0  bottom 5
5          2012     23     37673000.0  bottom 5
6          2013     28     48258000.0  bottom 5
7          2014     34     62728000.0  bottom 5
8          2015     43    113761000.0  bottom 5
9          2016     48    125238000.0  bottom 5
10         2017     52    145133000.0  bottom 5
11         2018     55    152339000.0  bottom 5
12         2019     63    178894000.0  bottom 5
13         2021     69    199286000.0  bottom 5
14         2022     74    211182000.0  bottom 5
15         2023     78    226703000.0  bottom 5
16         2024     85    249703000.0  bottom 5
17         2025     87    260703000.0  bottom 5
0          2006      4      5587000.0     top 5
1          2007      6     64627000.0     top 5
2          2008     11     87724000.0     top 5
3          2009     14     92369000.0     top 5
4          2010     17     96514000.0     top 5
5          2011     23    109286000.0     top 5
6          2012     31    124739000.0     top 5
7          2013     41    172278000.0     top 5
8          2014     50    194545000.0     top 5
9          2015     56    254810000.0     top 5
10         2016     70    306538000.0     top 5
11         2017     84    412623000.0     top 5
12         2018     95    452009000.0     top 5
13         2019    105    507525000.0     top 5
14         2020    107    509097000.0     top 5
15         2021    116    542348000.0     top 5
16         2022    122    552766000.0     top 5
17         2023    133    601374000.0     top 5
18         2024    140    623190000.0     top 5
19         2025    142    640690000.0     top 5
0          2006      5     15686000.0  middle 5
1          2008      9     28058000.0  middle 5
2          2009     11     32307000.0  middle 5
3          2010     17     40033000.0  middle 5
4          2011     27     61423000.0  middle 5
5          2012     29     63919000.0  middle 5
6          2013     39     71209000.0  middle 5
7          2014     52    112711000.0  middle 5
8          2015     72    171080000.0  middle 5
9          2016     85    223358000.0  middle 5
10         2017     94    259401000.0  middle 5
11         2018    126    436496000.0  middle 5
12         2019    137    467278000.0  middle 5
13         2020    151    507655000.0  middle 5
14         2021    156    509869000.0  middle 5
15         2022    167    530110000.0  middle 5
16         2023    178    582660000.0  middle 5
17         2024    187    623474000.0  middle 5
18         2025    189    638474000.0  middle 5

In [22]:
gb.to_csv('cleaned_data/parks-2006-2025.csv', index=False)

## NYC Planning Capital Projects

In [38]:
df_top5 = pd.read_csv('raw_data/top_5_capproj.csv')
df_top5.drop(columns = ['the_geom', 'the_geom_webmercator', 'magency', 'maprojid', 'magencyacro', 'sagencyacro'], inplace=True)
df_top5

,description,totalcommit,totalspend,maxdate,mindate,projecttype
0,360 ADAMS ST.- ELEVATOR MODERNIZATION ...,25513000,0.00,2029-06-01,2024-06-01,{Courts}
1,13 STAGE STITCHER/FOLDER/COLLATOR ...,143000,113844.14,2024-06-01,2013-02-11,{Police}
2,APICHA COMMUNITY HEALTH CENTER: initial outfit...,200000,0.00,2026-06-01,2026-06-01,"{""Health and Mental Hygiene""}"
3,NEVINS STREET PUMPING STATION ...,0,0.00,2025-06-01,2023-06-01,"{""Water Pollution Control""}"
4,St. Ann's Warehouse Automated Lighting ...,0,50000.00,2024-06-01,2013-09-30,"{""Cultural Affairs""}"
...,...,...,...,...,...,...
752,120 SCHERMERHORN ST.- CODE COMPLIANT TOILET UP...,2553000,0.00,2025-06-01,2022-10-01,{Courts}
753,911 SYSTEM UPGRADE - PSAC 1 Voice Alarm ...,10000000,1314715.11,2028-06-01,2019-12-09,"{""Fire Department""}"
754,NEWTOWN CREEK NATURE WALK PHASE 2 ...,0,11193150.10,2023-06-01,2012-11-19,"{""Water Pollution Control""}"
755,RENOVATE BLDG FOR RELOC OF BWSO NITE-OPS UNIT ...,0,62192.00,2023-06-01,2010-02-01,"{""Environmental Protection-Equipment""}"
756,Network Operations Center & Network Protector ...,145000,13631966.43,2027-06-01,2012-02-13,"{""Public Buildings""}"

In [39]:
df_bot5 = pd.read_csv('raw_data/bottom_5_capproj.csv')
df_bot5.drop(columns = ['the_geom', 'the_geom_webmercator', 'magency', 'maprojid', 'magencyacro', 'sagencyacro'], inplace=True)
df_bot5

,description,totalcommit,totalspend,maxdate,mindate,projecttype
0,Multi-Site Pedestrian Safety Phase 5 ...,1602000,452602.40,2028-06-01,2021-05-12,"{Highways,Traffic}"
1,MAIMONIDES MEDICAL CENTER: PURCHASE OF ULTRAS...,0,0.00,2024-06-01,2024-06-01,"{""Health and Mental Hygiene""}"
2,AQUEDUCT WALK - COMF. STATION X001-207M/507M ...,118000,1022985.17,2028-06-01,2010-01-19,"{""Water Mains, Sources and Treatment""}"
3,Maimonides Medical Center -Hospital Ambulances...,618000,0.00,2023-06-01,2023-06-01,"{""Health and Mental Hygiene""}"
4,KENSINGTON - Replacement Facility ...,0,13783338.10,2026-06-01,2010-03-10,"{""Brooklyn Public Library""}"
...,...,...,...,...,...,...
252,Manida Park-Lighting & Scoreboard Renovation ...,627000,0.00,2028-06-01,2023-02-01,"{""Parks and Recreation""}"
253,Hunts Point Meat Market 2 ...,31008000,13428170.22,2027-06-01,2018-03-06,"{""Economic Development""}"
254,UNION COMMUNITY HEALTH CENTER- PURCHASE MEDICA...,144000,0.00,2024-06-01,2024-06-01,"{""Health and Mental Hygiene""}"
255,Rugby - Branch Renovation ...,6000,6229751.36,2026-06-01,2010-08-09,"{""Brooklyn Public Library""}"
256,Recon fence at Friends Field Park ...,900000,0.00,2023-06-01,2023-06-01,"{""Parks and Recreation""}"

In [ ]:
# Some projects have no committed funding, this takes their totalspend instead
# These numbers were NOT in the calculation, with them the difference goes up to $6,267,676,214

mask = df_bot5["totalcommit"] == 0
df_bot5["totalcommit"] = df_bot5["totalcommit"].where(~mask, df_bot5["totalspend"])

mask = df_top5["totalcommit"] == 0
df_top5["totalcommit"] = df_top5["totalcommit"].where(~mask, df_top5["totalspend"])

,description,totalcommit,totalspend,maxdate,mindate,projecttype
0,Multi-Site Pedestrian Safety Phase 5 ...,1602000.0,452602.40,2028-06-01,2021-05-12,"{Highways,Traffic}"
1,MAIMONIDES MEDICAL CENTER: PURCHASE OF ULTRAS...,0.0,0.00,2024-06-01,2024-06-01,"{""Health and Mental Hygiene""}"
2,AQUEDUCT WALK - COMF. STATION X001-207M/507M ...,118000.0,1022985.17,2028-06-01,2010-01-19,"{""Water Mains, Sources and Treatment""}"
3,Maimonides Medical Center -Hospital Ambulances...,618000.0,0.00,2023-06-01,2023-06-01,"{""Health and Mental Hygiene""}"
4,KENSINGTON - Replacement Facility ...,13783338.1,13783338.10,2026-06-01,2010-03-10,"{""Brooklyn Public Library""}"
...,...,...,...,...,...,...
252,Manida Park-Lighting & Scoreboard Renovation ...,627000.0,0.00,2028-06-01,2023-02-01,"{""Parks and Recreation""}"
253,Hunts Point Meat Market 2 ...,31008000.0,13428170.22,2027-06-01,2018-03-06,"{""Economic Development""}"
254,UNION COMMUNITY HEALTH CENTER- PURCHASE MEDICA...,144000.0,0.00,2024-06-01,2024-06-01,"{""Health and Mental Hygiene""}"
255,Rugby - Branch Renovation ...,6000.0,6229751.36,2026-06-01,2010-08-09,"{""Brooklyn Public Library""}"
256,Recon fence at Friends Field Park ...,900000.0,0.00,2023-06-01,2023-06-01,"{""Parks and Recreation""}"

In [ ]:
top_sum = df_top5['totalcommit'].agg('sum')
bot_sum = df_bot5['totalcommit'].agg('sum')

top_sum - bot_sum

5847056000